# Generated by Django 4.2.2 on 2023-11-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
