# Generated by Django 4.2.7 on 2023-11-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
                ('title', models.CharField(max_length=20, verbose_name='상품명')),
                ('sales', models.IntegerField(verbose_name='가격')),
                ('place', models.CharField(max_length=20, verbose_name='거래장소')),
                ('account', models.CharField(max_length=20, verbose_name='계좌')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
