# Generated by Django 4.2.7 on 2023-11-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='계좌'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='post',
            name='place',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='거래장소'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sales',
            field=models.IntegerField(blank=True, null=True, verbose_name='가격'),
        ),
    ]
