# Generated by Django 4.2.7 on 2023-12-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='수량'),
        ),
    ]
