# Generated by Django 4.2.7 on 2023-11-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number',
            field=models.IntegerField(default=0, verbose_name='수량'),
        ),
    ]
