# Generated by Django 4.2.7 on 2023-12-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_number'),
        ('posts', '0004_alter_post_number_comment'),
    ]

    operations = [
    ]
