# Generated by Django 4.2.7 on 2023-12-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='people',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='인원수'),
        ),
    ]
